### PR TITLE
upgrade to support dbt-core v1.6.4

### PR DESCRIPTION
**Pull request by Dieken**
Actually this should work for dbt-core>=1.4.0 but I didn't test against old verions of dbt-core.

Tested against Python 3.8 and 3.11, TiDB 6.5.5.

See https://github.com/dbt-labs/dbt-core/discussions/6624

    XxxException -> DbtXxxError
    raise_compiler_error -> CompilationError

### CODE REVIEW

**Comment by Dieken** [comment]
Fixed #49 #50 #51.

**Comment by shiyuhang0** [comment]
@Dieken Can you fix the fmt by `pip3 install black` `black .`

**Comment by Dieken** [comment]
> @Dieken Can you fix the fmt by `pip3 install black` `black .`

Sure, done.

**Review by shiyuhang0 — APPROVED** [review]

**Comment by shiyuhang0** [comment]
Thanks for your contribute!

**Pull request merged**
